name: pymc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=hb9d3cd8_3
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py311h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311h331c9d8_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.11.9=h955ad1f_0
  - python_abi=3.11=2_cp311
  - pyzmq=25.1.2=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h9ecbd09_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - arviz==0.16.1
      - cachetools==5.5.0
      - cloudpickle==3.0.0
      - cons==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - etuples==0.3.9
      - fastprogress==1.0.3
      - filelock==3.15.4
      - fonttools==4.53.1
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - logical-unification==0.4.6
      - matplotlib==3.9.2
      - minikanren==1.0.3
      - multipledispatch==1.0.0
      - numpy==1.25.2
      - pandas==2.2.2
      - pillow==10.4.0
      - pymc==5.9.0
      - pyparsing==3.1.4
      - pytensor==2.17.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==1.5.1
      - scipy==1.12.0
      - seaborn==0.13.2
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - toolz==0.12.1
      - tqdm==4.66.5
      - tzdata==2024.1
      - watermark==2.4.3
      - xarray==2023.9.0
      - xarray-einstats==0.7.0
prefix: /home/users/u7212335/anaconda3/envs/pymc_env
